### ISSUE TITLE
Add/improve documentation site

### ISSUE THREAD

**Issue by Kronuz** [mechboxes/mech#25]
There's now https://mechboxes.github.io/mech/, but it needs documentation.

**Comment by jimoquinn** [comment]
I clicked the "improve this page" on the site above and I end up with a 404 not found.  Specifically on the Boxes page (https://mechboxes.github.io/mech/docs/boxes/).  Is there another way we can contribute?

**Comment by Kronuz** [comment]
You can do pull requests here in the repository, in the `gh-Pages` branch: 
https://github.com/mechboxes/mech/tree/gh-pages
