### ISSUE TITLE
ImportError: cannot import name 'Mech'

### ISSUE THREAD

**Issue by svanschalkwyk** [mechboxes/mech#36]
Resolved by building from git codebase.

Traceback (most recent call last):
  File "/usr/local/bin/mech", line 9, in <module>
    load_entry_point('mech==0.6', 'console_scripts', 'mech')()
  File "/home/steph/.local/lib/python3.5/site-packages/mech/__main__.py", line 32, in main
    from mech import Mech
ImportError: cannot import name 'Mech'

Linux Mint 18.xx
pip install

**Comment by arizvisa** [comment]
Is `python -m site --user-site` outputting that site-packages directory?

**Comment by svanschalkwyk** [comment]
$python -m site --user-site
/home/steph/.local/lib/python2.7/site-packages

**Comment by arizvisa** [comment]
looks like you installed mech in python3 site-packages path, and your default python installation is using python2?

**Comment by svanschalkwyk** [comment]
Sorry, this has been resolved (see first post) by building from source.
