### ISSUE TITLE
Provision Shell Script

### ISSUE THREAD

**Issue by wsc96** [mechboxes/mech#46]
Is there any documentation on the provision feature or a sample Mechfile that I can reference to do things like a provision shell script?

**Comment by dodo5522** [comment]
@wsc96 I'm new in this awesome tool mech, but I could provision VM with my below sample Mechfile. `"type": "file"` is just to copy a file from HOST to GEST VM. `"type": "shell"` is to run a script file on GEST VM.

```
{
  "box": "dodo5522/ubuntu-dev",
  "box_version": "1.0.1",
  "name": "mechtest",
  "url": "https://vagrantcloud.com/dodo5522/boxes/ubuntu-dev/versions/1.0.1/providers/vmware.box",
  "provision": [
    {   
      "type": "file",
      "source": "./temporary.txt",
      "destination": "/tmp/temporary.txt",
    },  
    {   
      "type": "shell",
      "path": "./apt.sh",
      "args": [], 
    },  
  ]
}
```
