### ISSUE TITLE
Wrong IP after certain VMs boot

### ISSUE THREAD

**Issue by ColdHeat** [mechboxes/mech#6]
https://github.com/vmware/open-vm-tools/issues/93

**Comment by ColdHeat** [comment]
This issue is undoubtedly the single most annoying issue I run into with mech. If I install docker inside of a virtual machine, vmrun will no longer find the IP address correctly and you end up having to go into Fusion to get the actual IP address

```
❯ mech up
Bringing machine up...
Getting IP address...
Sharing current folder...
VM started on 172.17.0.1
```

**Comment by Kronuz** [comment]
I was checking how this is done in Vagrant, it seems it also suffers from the same problem, they had/have (https://github.com/hashicorp/vagrant/issues/6580) and they added `enable_vmrun_ip_lookup`, which must be using a script to get the up, somehow. I wonder how they’re doing it...

**Comment by ColdHeat** [comment]
I don't like my current approach (changes to `getGuestIPAddress`), do you think this should be a change in vmrun or higher in mech/utils?

**Comment by ColdHeat** [comment]
I implemented an `enable_ip_lookup` as of https://github.com/mechboxes/mech/commit/e77d319abb0f552aa077d908b513eee5af155ebd
